# Generated by Django 5.2.17 on 2026-09-14 19:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_payable', 'view payable'), ('add_payable', 'add payable'), ('change_payable', 'change payable'), ('delete_payable', 'delete payable'), ('settle_payable', 'settle payable'), ('view_receivable', 'view receivable'), ('add_receivable', 'add receivable'), ('change_receivable', 'change receivable'), ('delete_receivable', 'delete receivable'), ('settle_receivable', 'settle receivable'), ('view_products', 'view products'), ('add_products', 'add products'), ('change_products', 'change products'), ('delete_products', 'delete products'), ('settle_products', 'settle products'), ('view_contacts', 'view contacts'), ('add_contacts', 'add contacts'), ('change_contacts', 'change contacts'), ('delete_contacts', 'delete contacts'), ('settle_contacts', 'settle contacts'), ('view_sales', 'view sales'), ('add_sales', 'add sales'), ('change_sales', 'change sales'), ('delete_sales', 'delete sales'), ('settle_sales', 'settle sales')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('customer', 'Cliente'), ('supplier', 'Fornecedor'), ('both', 'Cliente e fornecedor')], max_length=12, verbose_name='Tipo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='5565998040550', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{12,15}$', 'Use somente números, incluindo país e DDD.')], verbose_name='Seu WhatsApp (país + DDD + número)')),
                ('enabled', models.BooleanField(default=False, verbose_name='Ativar lembretes automáticos')),
                ('days_before', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Avisar quantos dias antes?')),
                ('hour', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='Horário do resumo (hora de Cuiabá)')),
                ('overdue', models.BooleanField(default=True, verbose_name='Incluir contas em atraso')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nome do produto')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='Código')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de venda')),
                ('notes', models.TextField(blank=True, verbose_name='Descrição')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payable', 'Conta a pagar'), ('receivable', 'Conta a receber')], max_length=10)),
                ('title', models.CharField(max_length=180, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due', models.DateField(verbose_name='Vencimento')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Categoria')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contact', verbose_name='Cliente / fornecedor')),
            ],
            options={
                'ordering': ['due', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('token', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.entry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('next_index', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='recurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.recurrence'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments', models.PositiveSmallIntegerField()),
                ('first_due', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.sale'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='entry_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('paid__gte', 0), ('paid__lte', models.F('amount'))), name='entry_paid_bounds'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('recurrence', 'sequence'), name='unique_recurrence_entry'),
        ),
    ]
