# Generated by Django 5.2.17 on 2026-09-14 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('source_file', models.CharField(max_length=255)),
                ('source_row', models.PositiveIntegerField()),
                ('original', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='import_origin', to='finance.entry')),
            ],
        ),
    ]
